### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by Son-Guhun** [Son-Guhun/JASS-Constant-Inliner#1]
- [ ] Make sure code still works after introducing the mpq module
- [ ] Make sure to run pjass after processing a file. Do not replace file if parsing fails.
- [ ] Create config file to store pjass and MPQEditor paths.
- [ ] Create a release with an executable
